### ISSUE TITLE
Typo in ch09-lists-tuples-and-dictionaries/6-store-relationships-in-dictionaries.py

### ISSUE THREAD

**Issue by relaxlex** [realpython/python-basics-exercises#21]
Hi,

in the solution file ch09-lists-tuples-and-dictionaries/6-store-relationships-in-dictionaries.py is typo in Bonus part of Exercise 3

`for name in ["Enterprise", "Discovery"]:`

should be

`for ship in ["Enterprise", "Discovery"]:`

Cheers,
-Lex

**Comment by dbader** [comment]
Fixed, thanks
